# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        BigPandaDev\MainBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    #providers:
    #    in_memory:
    #        memory: ~
    
    providers:
        our_db_provider:
            entity:
                class: BigPandaDevMainBundle:Users
                property: username
    
    firewalls:
        #login_firewall:
        #    pattern:   ^/login$
        #    anonymous: ~
        #secured_area:
        #    pattern:    ^/
        #    form_login: ~
        
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
    
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/lang, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #- { path: ^/test, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
        
    role_hierarchy:
        ROLE_CUSTOMER:    ROLE_USER
        ROLE_EMPLOYEE:    ROLE_USER
        ROLE_ADMIN:       [ROLE_EMPLOYEE, ROLE_CUSTOMER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
